// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdSSz_IODvmVP6kJABp09SRW3QIImlfIU',
    appId: '1:619371128320:web:14474348c1fd48ecdf1ae5',
    messagingSenderId: '619371128320',
    projectId: 'kariakoo-connect',
    authDomain: 'kariakoo-connect.firebaseapp.com',
    storageBucket: 'kariakoo-connect.appspot.com',
    measurementId: 'G-XK03N10GL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaTZAR9Hol375im199ZtwQBpcogMTNp40',
    appId: '1:619371128320:android:ba6c129751b03602df1ae5',
    messagingSenderId: '619371128320',
    projectId: 'kariakoo-connect',
    storageBucket: 'kariakoo-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBssb7kTgfb92NXswHH-YuR1gEoc5ja638',
    appId: '1:619371128320:ios:0721263501286099df1ae5',
    messagingSenderId: '619371128320',
    projectId: 'kariakoo-connect',
    storageBucket: 'kariakoo-connect.appspot.com',
    iosBundleId: 'kariakoo.connect.app',
  );
}